### ISSUE TITLE
Is there a way to attach screenshots into allure report when a protractor test fails?

### ISSUE THREAD

**Issue by carledriss** [allure-framework/allure-jasmine-plugin#1]

**Comment by ctapobep** [comment]
It won't be very different from making a screenshot with just protractor. You can take a look at [Protractor #114](https://github.com/angular/protractor/issues/114). The only difference - using `allure` object to attach files (take a look at the [sources](https://github.com/allure-framework/allure-js-commons/blob/master/runtime.js)) instead of simply putting it onto file system.

**Comment by carledriss** [comment]
I was able to attach the screenshot in the allure report 
but the screenshot is attached in a different test case
I have the following code

```
protractor.conf.js
var AllureReporter = require('jasmine-allure-reporter');
var allureReporter = new AllureReporter({
    allureReport: {
        resultsDir: 'allure-results'
    }
});

var addScreenShots = new function () {
    this.specDone = function (result) {
        if (result.status === "failed") {
            browser.takeScreenshot().then(function (png) {
                allure.createAttachment('Screenshot', function () {
                    return new Buffer(png, 'base64')
                }, 'image/png')();
            });
        }
    };
    //......
    onPrepare: function () {
        jasmine.getEnv().addReporter(allureReporter);
        jasmine.getEnv().addReporter(addScreenShots);
        //.......
    }
};
```
and this my report
![selection_201509a02d](https://cloud.githubusercontent.com/assets/3298869/9613316/99a1f64c-50b8-11e5-8d8f-22e99454d952.png)

Notice that the screenshot is attached in the next test case. when it should be attached to failed test case.

Could you help me? what is it wrong in my code?

**Comment by ctapobep** [comment]
Try placing reporters in different order:
```
        jasmine.getEnv().addReporter(addScreenShots);
        jasmine.getEnv().addReporter(allureReporter);
```

**Comment by carledriss** [comment]
The issue is still reproduced

**Comment by ctapobep** [comment]
I'll take a look at this tomorrow.

**Comment by ctapobep** [comment]
As for now I don't know how to solve the problem. browser.takeScreenshot() is a promise and therefore it will be executed asynchronously. By that time a test case (and even a test suite) may be finished. Maybe `yield` from ES6 can help, but I haven't tried this yet.

**Comment by ctapobep** [comment]
I found the solution:

```javascript
  onPrepare: function () {
    var AllureReporter = require('../../index.js');
    jasmine.getEnv().addReporter(new AllureReporter({
      resultsDir: 'allure-results'
    }));
    jasmine.getEnv().afterEach(function(done){
      browser.takeScreenshot().then(function (png) {
        allure.createAttachment('Screenshot', function () {
          return new Buffer(png, 'base64')
        }, 'image/png')();
        done();
      })
    });
  }
```

This takes screenshot after every test (not only the failed ones). Jasmine + Protractor wait for `afterEach()` to be finished before calling the reporters. The only strange thing - they don't wait if test passes, they wait only if test fails. Therefore I've added a callback `done()`.

@carledriss please give it a try.

**Comment by carledriss** [comment]
Yes, It is working now.
Thank you

Just in case. it would be better include this in the documentation

**Comment by jonsteuwart** [comment]
@ctapobep I am experiencing similar issue where the attachment comes into another test. Could you please take a look at this thread and see if you have any inputs?

https://github.com/allure-framework/allure-nunit2/issues/13

Many Thanks!

**Comment by ctapobep** [comment]
In our case it was a Jasmine-specific problem, it wasn't fixed by patches/workarounds in Allure.

**Comment by shivanthalakmal** [comment]
![image](https://cloud.githubusercontent.com/assets/7554175/24189493/3be35a1a-0f0b-11e7-8588-d4f8854966c4.png)

Any reason to can not find 'allure' module in typescript ? @ctapobep Could you help me? what is it wrong in my typescript code code?

**Comment by mike123vn** [comment]
@ctapobep: Is there any way get the name of each test and it screenshoot name. I want to delete the screenshoot of test passed

**Comment by ajaysuwalka** [comment]
@mike123vn  did you get any response to your query?

"Is there any way get the name of each test and it screenshoot name. I want to delete the screenshoot of test passed"

**Comment by sumeetp4** [comment]
Hey @ctapobep ,

I'm using allure reporter with webdrivio and mocha.

I need to have screenshot for my failed screenshot. Can you help me out here?

**Comment by Sereda-Fazen** [comment]
Hi everyone! Can you help me with attaching of screens in allure report. I have code

	```
	var AllureReporter = require('jasmine-allure-reporter');
   var allureReporter = new AllureReporter({
   allureReport: {
       resultsDir: 'report/allure-results'
   }
});
   var addScreenShots = new function () {
     this.specDone = function (result) {
       console.log(result)
         if (result.status === "failed") {    
             browser.takeScreenshot().then(function (png) {
                 allure.createAttachment('Screenshot', function () {
                     return new Buffer(png, 'base64')
                 }, 'image/png')();
             });
         }
     };
   }
   jasmine.getEnv().addReporter(addScreenShots);
   jasmine.getEnv().addReporter(allureReporter);
```
I got a screen in the folder with .xml files, but when I generate the report 
`allure generate ./allure-result/ --clean`
and 
`allure open`
I have no any screens in the report

**Comment by VladimirKovalenko** [comment]
Hello, I had the same issue and no simple code solution. 
Finally I managed with code which make screenshot only on failed tests and has no problem with asynchronous execution (when screen is attached to inappropriate test)
This code prom my protractor.conf.js

```
onPrepare() {
	var originalAddExpectationResult = jasmine.Spec.prototype.addExpectationResult;
	jasmine.Spec.prototype.addExpectationResult = function () {
		if (!arguments[0]) {
			browser.takeScreenshot().then(function (png) {
				allure.createAttachment('Screenshot', function () {
					return new Buffer(png, 'base64')
				}, 'image/png')();
			})
		}
		return originalAddExpectationResult.apply(this, arguments);
	};
	var AllureReporter = require('jasmine-allure-reporter');
	jasmine.getEnv().addReporter(new AllureReporter({
		resultsDir: 'allure-results',
	}));
}
```

**Comment by Sereda-Fazen** [comment]
Thanks a lot) It works. By the way have you ever used capabilities in console command for IE
for example for another browsers
```
protractor .\protractor.conf.js --suite test --browser=chrome
protractor .\protractor.conf.js --suite test --browser=firefox
protractor .\protractor.conf.js --suite test --browser=MicrosoftEdge
```
its works, but 
`protractor .\protractor.conf.js --suite test --browser=internet explorer
protractor .\protractor.conf.js --suite test --browser=ie
`
does not work, maybe someone faced with this problem?

**Comment by Sereda-Fazen** [comment]
Yeah I've got thought with this problem it is sufficiently to use ""
` protractor .\protractor.conf.js --suite test --browser="internet explorer"`
And that all

**Comment by Juani-Canete** [comment]
I'm using the next code in order to get allure failure screenshots only:

```
		const screenshootName = testName;
		const date = new Date();
		const day = date.getDate();
		const month = date.getMonth() + 1;
		const year = date.getFullYear();
		const hour = date.getHours();
		const minutes = date.getMinutes();
		const seconds = date.getSeconds();
		const humanReadableDate = `${day}/${month}/${year} ~ ${hour}:${minutes}:${seconds}`;
		browser.takeScreenshot().then(function(png) {
			allure.createAttachment(
				`${screenshootName} - ${humanReadableDate.trim()}`,
				function() {
					return new Buffer(png, 'base64');
				},
				'image/png',
			)();
		});
	};
```

And this is how it looks:
![image](https://user-images.githubusercontent.com/57629131/72943516-01cdcb00-3d55-11ea-961b-99b2be507f5b.png)



Something that I found, and is strange is that before adding this, I'd another screenshotter:
```
		const caps = await browser.getCapabilities();
		const browserName = await caps.get('browserName');
		const takeScreenshot = await browser.takeScreenshot();
		const stream = fse.createWriteStream(
			`logger-bag/screenshots-for-failures/${browserName} - ${result.fullName}.png`,
		);
		stream.write(new Buffer(takeScreenshot, 'base64'));
		stream.end();
```

Both in a secondary file, when I tried to run my tests using boths, the previous screenshot just started to fail, saying that the folder, does not exists, this is how I'm using them:


```
		specDone: async result => {
			if (result.status === 'failed') {
				ScreenshotsUtilities.allureScreenshot(allure, exports.config.multiCapabilities.name);
				ScreenshotsUtilities.takeScrenshootInFailure(result);
				}
```

I've the decition if I should use the allure ones, but for some strange reason sometimes the screenshot is not in the report, and happens only with a particular test:
![image](https://user-images.githubusercontent.com/57629131/72943798-bc5dcd80-3d55-11ea-9bf5-02cdbe96da23.png)

I've another test that's failing at the same way and the screenshot is there:
![image](https://user-images.githubusercontent.com/57629131/72943840-db5c5f80-3d55-11ea-8e3f-d483745df2b2.png)

**Comment by ronysoumen** [comment]
@VladimirKovalenko ur code is working for me..Thanx Buddy
