### ISSUE TITLE
Is there a way to generate the allure report using gulp instead of maven?

### ISSUE THREAD

**Issue by carledriss** [allure-framework/allure-jasmine-plugin#2]

**Comment by baev** [comment]
@carledriss see https://github.com/allure-framework/allure-core/wiki#generating-a-report

**Comment by baev** [comment]
so I guess you can use allure commandline client

**Comment by vania-pooh** [comment]
@carledriss so the short answer is no, we don't have gulp bindings. But the good news are that you can just call Allure CLI from your gulpfile.

**Comment by carledriss** [comment]
Thank you, I will generate the report using the Jenkins plugins

**Comment by ctapobep** [comment]
Would you please close the issue if it's not an issue for you anymore? :)
