### ISSUE TITLE
Question: Can we use "TestCase" or "TestCaseId" with jasmine plugin?

### ISSUE THREAD

**Issue by ravijammi** [allure-framework/allure-jasmine-plugin#8]
Hello,
I am trying out the jasmine plugin, and want to understand how to leverage "TestCase" or "TestCaseId" as this is supported by allure-core?
I am able to use other features like "createStep"/"description" etc, but not quite sure how we can use the testcase or testcaseid feature? 
Any pointers on this would be helpful.

Regards,
Ravi

**Comment by ctapobep** [comment]
I remember it was `allure.addLabel()`, don't remember which particular label name was used for testcases..

**Comment by just-boris** [comment]
Hello, @ravijammi.

Try this: 

```js
it('a test with label', function() {
   allure.addLabel('testId', 'YOUR-TEST-ID')
});
```

See related issue in commons module: https://github.com/allure-framework/allure-js-commons/issues/13

**Comment by ravijammi** [comment]
Hello @just-boris 
Thank you for the tip that worked, i do see the Test Case Id in the allure report now. 
I will go ahead an close this issue.

Thanks,
Ravi

**Comment by chinna1023** [comment]
How to add TMS pattern url using gradle for this?
